name: Selenium Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      - name: Run Selenium Tests
        run: mvn test

      - name: Upload TestNG Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: '**/test-output/testng-results.xml'

      - name: Send Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "❌ Selenium Tests Failed in GitHub Actions!"
